import time
from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
time.sleep(10)
driver.execute_script("window.scrollBy(0, 600)")
Selenium_Ruby_btn = driver.find_element_by_css_selector(".post-160 .woocommerce-LoopProduct-link")
Selenium_Ruby_btn.click()
time.sleep(5)
REVIEWS_btn = driver.find_element_by_css_selector(".reviews_tab")
REVIEWS_btn.click()
time.sleep(5)
star_btn = driver.find_element_by_css_selector(".star-5")
star_btn.click()
time.sleep(5)
Review_field = driver.find_element_by_id("comment")
Review_field.send_keys("Nice book")
Name_field = driver.find_element_by_id("author")
Name_field.send_keys("Ivan")
Email_field = driver.find_element_by_id("email")
Email_field.send_keys("ivanjulius@mail.com")
submit_btn = driver.find_element_by_id("submit")
submit_btn.click()
driver.quit()